<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>ProxyPython</name>
    <message>
        <location filename="proxy/proxypython.cpp" line="150"/>
        <source>Python Initialization failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="151"/>
        <source>On a previous start the Python Plugin failed to initialize.
Either the value in Settings-&gt;Plugins-&gt;ProxyPython-&gt;plugin_dir is set incorrectly or it is empty and auto-detection doesn&apos;t work for whatever reason.
Do you want to try initializing python again (at the risk of another crash)?
Suggestion: Select &quot;no&quot;, and click the warning sign for further help. Afterwards you have to re-enable the python plugin.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="194"/>
        <source>Proxy Plugin to allow plugins written in python to be loaded</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="269"/>
        <source>Python not installed or not found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="272"/>
        <source>Python version is incompatible</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="275"/>
        <source>Invalid python path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="278"/>
        <source>Initializing Python failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="281"/>
        <source>Python auto-detection failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="284"/>
        <source>ModOrganizer path contains a semicolon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="287"/>
        <source>invalid problem key %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="296"/>
        <source>Some MO plugins require the python interpreter to be installed. These plugins will not even show up in settings-&amp;gt;plugins.&lt;br&gt;If you want to use those plugins, please install the 32-bit version of Python 2.7.x from &lt;a href=&quot;%1&quot;&gt;%1&lt;/a&gt;.&lt;br&gt;This is only required to use some extended functionality in MO, you do not need Python to play the game.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="302"/>
        <source>Your installed python version has a different version than 2.7. Some MO plugins may not work.&lt;br&gt;If you have multiple versions of python installed you may have to configure the path to 2.7 (32 bit) in the settings dialog.&lt;br&gt;This is only required to use some extended functionality in MO, you do not need Python to play the game.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="309"/>
        <source>Please set python_dir in Settings-&gt;Plugins-&gt;ProxyPython to the path of your python 2.7 (32 bit) installation.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="312"/>
        <source>The auto-detection of the python path failed. I don&apos;t know why this would happen but you can try to fix it by setting python_dir in Settings-&gt;Plugins-&gt;ProxyPython to the path of your python 2.7 (32 bit) installation.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="316"/>
        <source>Sorry, I don&apos;t know any details. Most likely your python installation is not supported.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxy/proxypython.cpp" line="319"/>
        <source>The path to Mod Organizer (%1) contains a semicolon. &lt;br&gt;While this is legal on NTFS drives there is a lot of software that doesn&apos;t handle it correctly.&lt;br&gt;Unfortunately MO depends on libraries that seem to fall into that group.&lt;br&gt;As a result the python plugin can&apos;t be loaded.&lt;br&gt;The only solution I can offer is to remove the semicolon / move MO to a path without a semicolon.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
